config/routes.rb
Rails.application.routes.draw do
  root 'tickers#show'
  get 'orders', to: 'orders#show'
  get 'executions', to: 'executions#show'
  resources :buy_settings
  post 'buy_start', to: 'buy_settings#start'
  post 'buy_stop', to: 'buy_settings#stop'
  resources :sell_settings
  post 'sell_start', to: 'sell_settings#start'
  post   'sell_stop', to: 'sell_settings#stop'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy_setting.rb
class BuySetting < ApplicationRecord
end

app/models/execution.rb
class Execution < ApplicationRecord
  def self.latest
    Execution.all.limit(100)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  def self.latest
    Order.all.limit(100)
  end
end

app/models/sell_setting.rb
class SellSetting < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/ticker.rb
class Ticker < ApplicationRecord
  def self.latest
    Ticker.all.order(id: 'DESC').limit(100)
  end

  def self.get_old(minutes_num)
    Ticker.where('created_at <= ?', Time.now.utc - minutes_num.minutes).order(id: 'DESC').first
  end

  def self.delete_ticker
    Ticker.where(created_at: 1.week.ago.all_day).delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buy_settings_controller.rb
class BuySettingsController < ApplicationController
  before_action :set_buy_setting, only: [:edit, :update]

  # GET /buy_settings
  # GET /settings.json
  def index
    @buySetting = BuySetting.first
  end

  # GET /buy_settings/new
  def new
    @buySetting = BuySetting.new
  end

  # GET /buy_settings/1/edit
  def edit
  end

  # POST /buy_settings
  # POST /buy_settings.json
  def create
    @buySetting = BuySetting.new(buy_setting_params)

    respond_to do |format|
      if @buySetting.save
        format.html { redirect_to buy_settings_url, notice: 'BuySetting was successfully created.' }
        format.json { render :show, status: :created, location: @buySetting }
      else
        format.html { render :new }
        format.json { render json: @buySetting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buy_settings/1
  # PATCH/PUT /buy_settings/1.json
  def update
    respond_to do |format|
      if @buySetting.update(buy_setting_params)
        format.html { redirect_to buy_settings_url, notice: 'BuySetting was successfully updated.' }
        format.json { render :show, status: :ok, location: @buySetting }
      else
        format.html { render :edit }
        format.json { render json: @buySetting.errors, status: :unprocessable_entity }
      end
    end
  end

  def start
    buySetting = BuySetting.first
    buySetting.is_execution = true
    respond_to do |format|
      if buySetting.save
        format.html { redirect_to buy_settings_url, notice: 'BuySetting was successfully updated.' }
        format.json { render :show, status: :ok, location: buySetting }
      else
        format.html { render :show }
        format.json { render json: buySetting.errors, status: :unprocessable_entity }
      end
    end
  end

  def stop
    buySetting = BuySetting.first
    buySetting.is_execution = false
    respond_to do |format|
      if buySetting.save
        format.html { redirect_to buy_settings_url, notice: 'BuySetting was successfully updated.' }
        format.json { render :show, status: :ok, location: buySetting }
      else
        format.html { render :show }
        format.json { render json: buySetting.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_buy_setting
    @buySetting = BuySetting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def buy_setting_params
    params.require(:buy_setting).permit(:minutes, :reduction_percent, :jpy, :buy_count, :exec_date)
  end
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  def show
    @executions = Execution.latest
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @orders = Order.latest
  end
end

app/controllers/sell_settings_controller.rb
class SellSettingsController < ApplicationController
  before_action :set_sell_setting, only: [:edit, :update]

  # GET /sell_settings
  # GET /settings.json
  def index
    @sellSetting = SellSetting.first
  end

  # GET /sell_settings/new
  def new
    @sellSetting = SellSetting.new
  end

  # GET /sell_settings/1/edit
  def edit
  end

  # POST /sell_settings
  # POST /sell_settings.json
  def create
    @sellSetting = SellSetting.new(sell_setting_params)

    respond_to do |format|
      if @sellSetting.save
        format.html { redirect_to sell_settings_url, notice: 'SellSetting was successfully created.' }
        format.json { render :show, status: :created, location: @sellSetting }
      else
        format.html { render :new }
        format.json { render json: @sellSetting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sell_settings/1
  # PATCH/PUT /sell_settings/1.json
  def update
    respond_to do |format|
      if @sellSetting.update(sell_setting_params)
        format.html { redirect_to sell_settings_url, notice: 'SellSetting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sellSetting }
      else
        format.html { render :edit }
        format.json { render json: @sellSetting.errors, status: :unprocessable_entity }
      end
    end
  end

  def start
    sellSetting = SellSetting.first
    sellSetting.is_execution = true
    respond_to do |format|
      if sellSetting.save
        format.html { redirect_to sell_settings_url, notice: 'SellSetting was successfully updated.' }
        format.json { render :show, status: :ok, location: sellSetting }
      else
        format.html { render :show }
        format.json { render json: sellSetting.errors, status: :unprocessable_entity }
      end
    end
  end

  def stop
    sellSetting = SellSetting.first
    sellSetting.is_execution = false
    respond_to do |format|
      if sellSetting.save
        format.html { redirect_to sell_settings_url, notice: 'SellSetting was successfully updated.' }
        format.json { render :show, status: :ok, location: sellSetting }
      else
        format.html { render :show }
        format.json { render json: sellSetting.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sell_setting
    @sellSetting = SellSetting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sell_setting_params
    params.require(:sell_setting).permit(:minutes, :increase_percent, :bitcoin, :sell_count, :exec_date)
  end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  def show
    @tickers = Ticker.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_settings_helper.rb
module BuySettingsHelper
end

app/helpers/executions_helper.rb
module ExecutionsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sell_settings_helper.rb
module SellSettingsHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/views/buy_settings/_form.html.slim
= form_for @buySetting do |f|
  - if @buySetting.errors.any?
    #error_explanation
      h2 = "#{pluralize(@buySetting.errors.count, "error")} prohibited this setting from being saved:"
      ul
        - @buySetting.errors.full_messages.each do |message|
          li = message

  .form-group
    .field
      = f.label :minutes, '取引間隔（分）'
      = f.number_field :minutes, class: 'form-control'
  .form-group
    .field
      = f.label :buy_count, '数量（買）'
      = f.text_field :buy_count, class: 'form-control'
  .form-group
    .field
      = f.label :reduction_percent, '減少率'
      = f.text_field :reduction_percent, class: 'form-control'
  .form-group
    .field
      = f.label :jpy, '現金保有数（万円）'
      = f.number_field :jpy, class: 'form-control'
  .row
    .col-md-1
      .actions = f.submit '更新', class: 'btn btn-primary'
    .col-md-1
      = link_to '戻る', buy_settings_path, class: 'btn btn-secondary'

app/views/buy_settings/edit.html.slim
h1 Editing BuySetting
== render 'form'

app/views/buy_settings/index.html.slim
h1 BuySetting

p ※1 画面下部の表と以下の説明は連動しています。条件をよく確認して不備がないかご確認ください。
p ※2 取引間隔は分計算しておりますので、お間違いのないようご注意ください。例 720分/12時間 1440分/1日 43200分/30日

h4 現在の買い条件
.jumbotron
  p 現在時間より ”#{@buySetting ? @buySetting.minutes : ''}” 分前の時点（取引頻度）の最終取引価格より,”#{@buySetting ? @buySetting.reduction_percent : ''}”%減少（減少率）しているかつ
    総資産の保有数が”#{@buySetting ? @buySetting.jpy : ''}” 万円（売り条件）以上の場合、”#{@buySetting ? @buySetting.buy_count : ''}” bit coin(数量（買）)を買います。
- unless @buySetting
  p = link_to '新規作成', new_buy_setting_path , class: 'btn btn-primary'
- else
  = form_with url: buy_start_path do |form|
    .form-group
      .field
        = form.label '定期的に買い取引を開始したい場合、こちらのボタンを押してください。'
        = form.submit '取引開始', class: 'btn btn-primary'

  = form_with url: buy_stop_path do |form|
    .form-group
      .field
        = form.label '定期的な買い取引を停止したい場合、こちらのボタンを押してください。'
        = form.submit '取引停止', class: 'btn btn-danger'

table.table
  thead.thead-dark
    tr
      th 取引間隔（分）
      th 数量（買）
      th 減少率
      th 現金保有数（万円）
      th 取引状態
      th 最終取引時間
      th

  tbody
    - if @buySetting
      tr
        td = @buySetting.minutes
        td = @buySetting.buy_count
        td = @buySetting.reduction_percent
        td = @buySetting.jpy
        td = @buySetting.is_execution ? '開始' : '停止'
        td = @buySetting.exec_date
        td = link_to '編集', edit_buy_setting_path(@buySetting)

app/views/buy_settings/new.html.slim
h1 Create BuySetting
== render 'form'

app/views/executions/show.html.slim
h1 Executions

table.table
  thead.thead-dark
    tr
      th Child Order ID
      th 注文タイプ
      th 価格
      th SIZE
      th 手数料
      th 実行時間
  tbody
    - @executions.each do |execution|
      tr
        td = execution.child_order_id
        td = execution.side
        td = execution.price
        td = execution.size
        td = execution.commission
        td = execution.exec_date.in_time_zone('Asia/Tokyo')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AutoTrading
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  .nav.navbar.navbar-expand-sm.bg-dark.navbar-dark
    .container
      h3.navbar-brand AutoTradingApp
      ul.navbar-nav
        li.nav-item
          = link_to 'Tickers', root_path, class: 'nav-link'
        li.nav-item
          = link_to 'Orders', orders_path, class: 'nav-link'
        li.nav-item
          = link_to 'Executions', executions_path, class: 'nav-link'
        li.nav-item
          = link_to 'BuySetting', buy_settings_path, class: 'nav-link'
        li.nav-item
          = link_to 'SellSetting', sell_settings_path, class: 'nav-link'
  body
    .container
      p.notice
        = notice
      p.alert
        = alert
      = yield

app/views/orders/show.html.slim
h1 Orders
table.table
  thead.thead-dark
    tr
      th Child Order ID
      th 銘柄
      th 取引内容
      th 注文タイプ
      th 価格
      th 価格平均
      th SIZE
      th オーダ状況
      th オーダー日
  tbody
    - @orders.each do |order|
      tr
        td = order.child_order_id
        td = order.product_code
        td = order.side
        td = order.child_order_type
        td = order.price
        td = order.average_price
        td = order.size
        td = order.child_order_state
        td = order.child_order_date

app/views/sell_settings/_form.html.slim
= form_for @sellSetting do |f|
  - if @sellSetting.errors.any?
    #error_explanation
      h2 = "#{pluralize(@sellSetting.errors.count, "error")} prohibited this setting from being saved:"
      ul
        - @sellSetting.errors.full_messages.each do |message|
          li = message

  .form-group
    .field
      = f.label :minutes, '取引間隔（分）'
      = f.number_field :minutes, class: 'form-control'
  .form-group
    .field
      = f.label :sell_count, '数量（売）'
      = f.text_field :sell_count, class: 'form-control'
  .form-group
    .field
      = f.label :increase_percent, '増加率'
      = f.text_field :increase_percent, class: 'form-control'
  .form-group
    .field
      = f.label :bitcoin, 'Bitcoin保有数'
      = f.text_field :bitcoin, class: 'form-control'
  .row
    .col-md-1
      .actions = f.submit '更新',class: 'btn btn-primary'
    .col-md-1
      = link_to '戻る', buy_settings_path, class: 'btn btn-secondary'

app/views/sell_settings/edit.html.slim
h1 Editing SellSetting
== render 'form'

app/views/sell_settings/index.html.slim
h1 SellSetting

p ※1 画面下部の表と以下の説明は連動しています。条件をよく確認して不備がないかご確認ください。
p ※2 取引間隔は分計算しておりますので、お間違いのないようご注意ください。例 720分/12時間 1440分/1日 43200分/30日

h4 現在の売り条件
.jumbotron
  p 現在時間より ”#{@sellSetting ? @sellSetting.minutes : ''}” 分前の時点（取引頻度）の最終取引価格より,”#{@sellSetting ? @sellSetting.increase_percent : ''}”%上昇（増加率）しているかつ
    ビットコインの保有数が”#{@sellSetting ? @sellSetting.bitcoin : ''}” bit coin（売り条件）以上の場合、”#{@sellSetting ? @sellSetting.sell_count : ''}” bit coin(数量（売）)を売ります。
- unless @sellSetting
  p = link_to '新規作成', new_sell_setting_path, class: 'btn btn-primary'

- else
  = form_with url: sell_start_path do |form|
    .form-group
      .field
        = form.label '定期的に売り取引を開始したい場合、こちらのボタンを押してください。'
        = form.submit '取引開始', class: 'btn btn-primary'

  = form_with url: sell_stop_path do |form|
    .form-group
      .field
        = form.label '定期的な売り取引を停止したい場合、こちらのボタンを押してください。'
        = form.submit '取引停止', class: 'btn btn-danger'

table.table
  thead.thead-dark
    tr
      th 取引間隔（分）
      th 数量（売）
      th 増加率
      th Bitcoin保有数
      th 取引状態
      th 最終取引時間
      th

  tbody
    - if @sellSetting
      tr
        td = @sellSetting.minutes
        td = @sellSetting.sell_count
        td = @sellSetting.increase_percent
        td = @sellSetting.bitcoin
        td = @sellSetting.is_execution ? '開始' : '停止'
        td = @sellSetting.exec_date
        td = link_to '編集', edit_sell_setting_path(@sellSetting)

app/views/sell_settings/new.html.slim
h1 Create SellSetting
== render 'form'

app/views/tickers/show.html.slim
h1 Tickers

table.table
  thead.thead-dark
    tr
      th ID
      th 銘柄
      th 最終取引価格
      th 確認日時
      th 最高買い価格
      th 最低売り価格
      th 買い注文総数
      th 売り注文総数
  tbody
    - @tickers.each do |ticker|
      tr
        td = ticker.id
        td = ticker.product_code
        td = ticker.ltp
        td = ticker.timestamp.in_time_zone('Asia/Tokyo')
        td = ticker.best_ask
        td = ticker.best_bid
        td = ticker.total_ask_depth
        td = ticker.total_bid_depth